name: build_container

on:
  workflow_call:
    inputs:
      git_tag:
        required: true
        type: string
      docker_container_uri_str_list:
        required: true
        type: string
      index_url:  # Use test pypi index when downloading from dev
        required: true
        type: string

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use qemu to perform multiplatform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Use docker buildx to build multi-platform containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      # Log in to GitHub Container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Build and push docker images
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            V2_SAMPLESHEET_MAKER_VERSION_TAG=${{ inputs.git_tag }}
            INDEX_URL=${{ inputs.index_url }}
          tags: ${{ inputs.docker_container_uri_str_list }}