name: build-package-wheel-and-release

on:
  workflow_call:
    inputs:
      git_tag:
        required: true
        type: string
      pypi_repository:
        required: true
        type: string
      is_pre_release:
        required: true
        type: string

permissions:
  id-token: write   # This is required for connecting to PYPI
  contents: read    # This is required for actions/checkout

jobs:
  deploy_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - id: git_checkout
        uses: actions/checkout@4
      # Used to host cibuildwheel
      - id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - id: download_wheels
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.dist_artifacts_name }}
      - id: install_deployment_deps
        run: |
          pip install .[deploy]
      - id: deploy_to_pypi
        run: |
          if [[ "${{ inputs.is_pre_release }}" == "true" ]]; then
            make push_test_pypi
          else
            make push_pypi
          fi
      - id: check_successful_deployment_to_pypi
        run: |
          if [[ "${{ inputs.is_pre_release }}" == "true" ]]; then
            make install_test_pypi
          else
            make install_pypi
          fi